#!/usr/bin/env python3
"""Writes a header naming the commit the Android host is built from (the Vulkan
probe's report prints it; port/android/host/host_vk_probe.c).

    android_build_stamp.py <header>

Run by ninja on every build (tools/android_build.py), so the name is the tree's
as it is built, not as it was when configure.py last ran. The header is only
rewritten when the name changes, and the rule restats it, so an unchanged tree
recompiles nothing.
"""

import subprocess
import sys
from pathlib import Path


def describe() -> str:
    try:
        head = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True,
                              check=True).stdout.strip()
        dirty = subprocess.run(["git", "status", "--porcelain", "--untracked-files=no"], capture_output=True,
                               text=True, check=True).stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return "unknown"
    return head + ("+changes" if dirty else "")


def main() -> None:
    header = Path(sys.argv[1])
    text = f'/* generated by tools/android_build_stamp.py */\n#define HALO_PROBE_BUILD "{describe()}"\n'
    if not header.exists() or header.read_text() != text:
        header.parent.mkdir(parents=True, exist_ok=True)
        header.write_text(text)


if __name__ == "__main__":
    main()
